# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo ok
  displayName: 'Run a one-line script'

- checkout: self

- script: |
    chmod +x debian_setup.sh;
    sudo ./debian_setup.sh
  displayName: 'run script'
